# Generated by Django 5.0.3 on 2024-05-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_generalsetting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
