# Generated by Django 5.0.3 on 2024-05-14 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_generalsetting_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'General Settings', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.CharField(blank=True, default='', help_text='This is for name', max_length=100),
        ),
    ]
