# Generated by Django 5.0.3 on 2024-05-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='This is for name', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=254)),
                ('file', models.ImageField(blank=True, default='', upload_to='media/img', verbose_name='Image')),
            ],
        ),
    ]
