# Generated by Django 5.0.3 on 2024-05-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='img/', verbose_name='Image'),
        ),
    ]
